version: "2"
services:
  traefik:
    image: marcopaga/traefik:1.3.5.1
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO 
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - "traefik.enable=false"
  whoami:
    image: emilevauge/whoami 
    labels:
    - "traefik.backend=whoami"
    - "traefik.frontend.rule=Host:whoami.docker.localhost"
